# Example generated by the backend:
#{
#  "game": "quakejs",
#  "deployment_target": "aws",
#  "instance_type": "t3.small",
#  "region": "eu-central-1",
#  "ssh_key_name": "my-ec2-keypair",
#  "http_port": 8080,
#  "game_port": 27960,
#  "game_slots": 12
#}

variable "game" {
  type        = string
  description = "Game to deploy (quakejs, minecraft, csgo)"
}

variable "deployment_target" {
  type        = string
  description = "Deployment environment (aws, gcp, local)"
}

variable "instance_type" {
  type        = string
  default     = "t3.small"
  description = "Cloud instance type"
}

variable "region" {
  type        = string
  default     = "eu-central-1"
  description = "Cloud region"
}

variable "ssh_key_name" {
  type        = string
  description = "Name of the EC2 key pair to use for SSH access. Must exist in the selected region."
  default     = null # Or provide a default if you have a common one
}

variable "http_port" {
  type        = number
  default     = 8080
  description = "External TCP port for game's web interface."
}

variable "game_port" {
  type        = number
  default     = 27960 # Default for Quake, will be overridden by other games or specific settings
  description = "Primary external game port (often UDP)."
}

variable "game_slots" {
  type        = number
  default     = 12
  description = "Number of player slots for the game server."
}


