# Examplegenerated by the backend:
#{
#  "game": "quakejs",
#  "deployment_target": "aws",
#  "instance_type": "t3.small",
#  "region": "eu-central-1",
#  "http_port": 8080,
#  "game_slots": 12
#}

variable "game" {
  type        = string
  description = "Game to deploy (quakejs, minecraft, csgo)"
}

variable "deployment_target" {
  type        = string
  description = "Deployment environment (aws, gcp, local)"
}

variable "instance_type" {
  type        = string
  default     = "t3.small"
  description = "Cloud instance type (ignored if local)"
}

variable "region" {
  type        = string
  default     = "eu-central-1"
  description = "Cloud region"
}

variable "http_port" {
  type        = number
  default     = 8080
}

variable "game_slots" {
  type        = number
  default     = 12
}

